### ISSUE TITLE
Excited to see the 3D implementation 

### ISSUE THREAD

**Issue by peterlionelnewman** [wwsource/SplatFlow3D#1]
Hi, I’m currently working on the study of 3d flows, and would love to try out your algorithm. Let me know if there’s something I can do to help with testing or getting this up and running. Thanks,

**Comment by wwsource** [comment]
Thank you for noticing our work!
The paper for SplatFlow3D is currently under review. Once there is any latest progress in the review, we will inform you immediately. Meanwhile, you can refer to [SplatFlow](https://github.com/wwsource/SplatFlow) and [SceneTracker](https://github.com/wwsource/SceneTracker), which have contributed significant design inspirations to SplatFlow3D. 
Thank you for your understanding~

**Comment by peterlionelnewman** [comment]
Thanks and good luck with your submission - hope that there a minimal issues!

**Comment by wwsource** [comment]
Thank you for your wishes!
